### ISSUE TITLE
no license specified

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/mmfd#14]
this package is missing a license specification.
please chose one and get approval from every other author that contributed to this software.

**Comment by christf** [comment]
in mmfd the master branch are commets by @tcatm @lemoer  and myself.
I am happy to release my commints under LGPL. What are your thoughts on this one?

**Comment by rotanid** [comment]
Gluon uses the BSD 2-clause license, just for reference

**Comment by lemoer** [comment]
My contributions are minor, so I don't really have a strong oppinion.

**Comment by rotanid** [comment]
@tcatm what's the license on your commits?
@lemoer so BSD 2-clause for simplicity on your commits is ok?

**Comment by tcatm** [comment]
Please consider all code I wrote in relation to Freifunk as public domain.

**Comment by rotanid** [comment]
thanks!
@christf would you also be OK with BSD 2-clause like we have it for Gluon and l3roamd?

**Comment by lemoer** [comment]
> @lemoer so BSD 2-clause for simplicity on your commits is ok?

:+1:

**Comment by christf** [comment]
now that this is settled, the BSD 2-clause license should be specified in this repo.

**Comment by rotanid** [comment]
> now that this is settled, the BSD 2-clause license should be specified in this repo.

done.

**Comment by christf** [comment]
On Sun, Jul 21, 2019 at 06:27:23AM -0700, Andreas Ziegler wrote:
>> now that this is settled, the BSD 2-clause license should be specified in this repo.
>
>done.
Thank you.
-- 
()  ascii ribbon campaign - against html e-mail
/\  www.asciiribbon.org   - against proprietary attachments
